[package]
name = "nrf52840-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rtic = "1.0.0"
board = { path = "../board"}
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }

# Temporary, general purpose - two below are more correct
systick-monotonic = "1.0.0"
#fugit = "0.3.3"
#rtic-monotonic = "1.0.0"

[dependencies.nrf52840-hal]
version = "0.15.0"
default-features = false
features = ["rt"]


